from app.services.gemini_service import BaseService


class CharacterService(BaseService):
    def generate_character(self, description, level, fixed_race=None, fixed_class=None):

        race_instruction = f"La raza DEBE ser {fixed_race}." if fixed_race else "Elige una raza apropiada."
        class_instruction = f"La clase DEBE ser {fixed_class}." if fixed_class else "Elige una clase apropiada."

        system_instruction = """
        You are an expert D&D 5e (2024) character designer.
        Generate a complete player character (PC) with combat stats.
        
        Always respond with this valid JSON (English snake_case):
        {
            "name": "Character Name",
            "race": "Race",
            "class": "Class",
            "level": 1,
            "alignment": "e.g: Neutral Good",
            "ca": 15,
            "hp": 35,
            "speed": 30,
            "stats": { "STR": 15, "DEX": 14, "CON": 13, "INT": 12, "WIS": 10, "CHA": 8 },
            "attacks": [
                {
                    "name": "Main Attack",
                    "type": "melee",
                    "bonus": 4,
                    "damage": "1d8 + 2",
                    "damage_type": "slashing"
                }
            ],
            "skills": ["Athletics +4", "Perception +2"],
            "personality": { "trait": "...", "ideal": "...", "bond": "...", "flaw": "..." },
            "background": "Brief character history",
            "equipment": ["Longsword", "Leather Armor", "Backpack"]
        }
        """

        prompt = f"""
        Create a D&D 5e character based on this description: "{description}"
        - Level: {level}
        - {race_instruction}
        - {class_instruction}
        
        Ensure stats are appropriate for level and class.
        Include interesting personality and brief background.
        
        CRITICAL: Use English keys (snake_case).
        Do NOT use Spanish keys.
        Return ONLY valid JSON.
        """

        result = self._generate_content(system_instruction, prompt)
        print(f"👤 Character generated by Gemini: {result}")  # DEBUG
        return result


character_service = CharacterService()
