from app.services.gemini_service import BaseService


class InnService(BaseService):
    def generate_inn(self, name, comfort_level, theme, city=""):
        context_city = ""
        if city:
            context_city = f"La posada se encuentra en la ciudad de: {city}. ADAPTA la comida, bebida y ambiente a la cultura y geografía de esa ciudad."

        system = """
        You are an expert D&D world builder. Generate a detailed inn.
        Always respond with this exact JSON (English snake_case) English keys and Spanish values:
        {
            "name": "Inn Name",
            "location": "City or place",
            "description": "Sensory description (smells, lighting, ambiance).",
            "comfort_level": "Poor/Modest/Rich...",
            "innkeeper_name": "Name",
            "innkeeper_race": "Race",
            "innkeeper_personality": "Distinctive trait or secret.",
            "menu": [
                {"name": "Dish/Drink Name", "price": "X cp/sp/gp", "description": "Brief description"}
            ],
            "rooms": [
                {"type": "Common/Private", "price": "X gp", "description": "Bed condition."}
            ],
            "notable_patrons": ["A sad bard", "Two drunk guards"],
            "rumor": "A local gossip or adventure hook heard at the bar."
        }
        """

        prompt = f"""
        Generate an inn with comfort level "{comfort_level}" and theme "{theme}".
        {(f'The name must be: {name}' if name else 'Invent a creative name.')}
        {context_city}
        Ensure menu and room prices are coherent with comfort level "{comfort_level}" (per D&D 5e).
        
        CRITICAL: Use English keys (snake_case) English keys and Spanish values:
        "name", "location", "description", "comfort_level", "innkeeper_name", "innkeeper_race", 
        "innkeeper_personality", "menu" (array), "rooms" (array), "notable_patrons", "rumor"
        Return ONLY valid JSON.
        """

        result = self._generate_content(system, prompt)
        print(f"[LOG] Inn generated by Gemini: {result}")  # DEBUG
        return result


inn_service = InnService()