from app.services.gemini_service import BaseService


class ItemService(BaseService):
    def generate_item(self, item_type, rarity, attunement=False, name=""):
        attunement_str = "Requires attunement." if attunement else "Does NOT require attunement."
        name_instruction = f"The item must be named '{name}'." if name else "Invent a mystical and unique name."

        system = """
        You are an arcane master armorer for D&D 5e (2024). Generate a magical item.
        Respond ONLY with this exact JSON (English snake_case):
        {
            "name": "Item Name",
            "type": "Type (Sword, Ring, etc)",
            "rarity": "Rarity",
            "attunement": true/false,
            "description": "Detailed physical and visual description.",
            "mechanics": "Game rules, bonuses, damage and magical effects (D&D 5e).",
            "value": "Estimated price in gp"
        }
        """

        prompt = f"""
        Generate a magical item with these characteristics:
        - Type: {item_type}
        - Rarity: {rarity}
        - {attunement_str}
        - {name_instruction}

        Ensure mechanics are balanced for the rarity.
        
        CRITICAL: Use English keys (snake_case):
        "name", "type", "rarity", "attunement", "description", "mechanics", "value"
        DO NOT use Spanish keys like "nombre", "sintonizacion", etc.
        """

        result = self._generate_content(system, prompt)
        print(f"⚔️ Item generated by Gemini: {result}")  # DEBUG
        return result


item_service = ItemService()