from app.services.gemini_service import BaseService


class ItemService(BaseService):
    def generate_item(self, item_type, rarity, attunement=False, name=""):
        attunement_str = "Requires attunement." if attunement else "Does NOT require attunement."
        name_instruction = f"The item must be named '{name}'." if name else "Invent a mystical and unique name."

        system = """
        You are an arcane master armorer for D&D 5e (2024). Generate a magical item.
        Respond ONLY with this exact JSON (English snake_case) Values en Español:
        {
            "name": "Item Name",
            "type": "Type (Sword, Ring, etc)",
            "rarity": "Rarity",
            "attunement": true/false,
            "description": "Detailed physical and visual description.",
            "mechanics": "MANDATORY: Game rules, bonuses, damage and magical effects (D&D 5e). Be specific with dice rolls and effects.",
            "class_requirement": "Which character class benefits most from this item, or 'Cualquier clase' if universal",
            "value": "Estimated price in gp"
        }
        """

        prompt = f"""
        Generate a magical item with these characteristics:
        - Type: {item_type}
        - Rarity: {rarity}
        - {attunement_str}
        - {name_instruction}

        IMPORTANT REQUIREMENTS:
        1. Mechanics MUST NOT be empty or null. Always include specific D&D 5e rules and effects.
        2. Include precise numbers: dice rolls (like 1d6+2), damage types, durations, saving throws, etc.
        3. Suggest which class (Barbarian, Bard, Cleric, Druid, Fighter, Monk, Paladin, Ranger, Rogue, Sorcerer, Warlock, Wizard) would benefit most.
        
        CRITICAL: Use English keys (snake_case) Values en Español:
        "name", "type", "rarity", "attunement", "description", "mechanics", "class_requirement", "value"
        DO NOT use Spanish keys like "nombre", "sintonizacion", etc.
        """

        result = self._generate_content(system, prompt)
        print(f"[LOG] Item generated by Gemini: {result}")  # DEBUG
        return result


item_service = ItemService()