from app.services.gemini_service import BaseService


class MonsterService(BaseService):
    def generate_monster(self, base_monster, theme, target_cr=None):
        cr_instruction = ""
        if target_cr:
            cr_instruction = f"ADJUST STAT PRIORITY (HP, AC, Damage) so the monster is Challenge (CR) {target_cr}."

        system = """
        You are a veteran D&D 5e (2024) monster designer.
        Your job is to apply thematic "templates" to existing monsters, modifying their stats and abilities.

        Return ALWAYS a valid JSON with this EXACT structure (English snake_case):
        {
            "name": "New Monster Name",
            "type": "Type (e.g: Humanoid, Aberration)",
            "alignment": "Alignment",
            "ca": 15,
            "hp": "50 (6d10 + 20)",
            "speed": "30 ft.",
            "stats": { "STR": 10, "DEX": 10, "CON": 10, "INT": 10, "WIS": 10, "CHA": 10 },
            "saves": "STR +5, CON +4 (Optional)",
            "skills": "Perception +3 (Optional)",
            "senses": "Darkvision 60 feet",
            "languages": "Common",
            "cr": "3 (700 XP)",
            "traits": [ 
                {"name": "Trait Name", "desc": "Trait description."} 
            ],
            "actions": [ 
                {"name": "Attack Name", "desc": "Melee weapon attack: +5 to hit, 1d8+3 damage."} 
            ],
            "visual": "Brief description of appearance for DM to read aloud."
        }
        """

        prompt = f"""
        Take the base monster "{base_monster}" and apply the template/theme "{theme}".
        {cr_instruction}
        Change its attacks and traits to reflect the new theme.
        
        CRITICAL: Return EXACTLY JSON with English keys (snake_case).
        Use: "name", "stats", "alignment", NOT Spanish variants.
        """

        result = self._generate_content(system, prompt)
        print(f"👹 Monster generated by Gemini: {result}")  # DEBUG
        return result


monster_service = MonsterService()