from app.services.gemini_service import BaseService


class ShopService(BaseService):
    def generate_shop(self, shop_type, level=1, location=""):

        context_loc = ""
        if location:
            context_loc = f"La tienda está ubicada en la ciudad de: {location}. ADAPTA el inventario, los precios y la raza del tendero a la cultura de esa ciudad."

        # Instrucciones de escalado de nivel para D&D 5e
        level_guidance = ""
        if level <= 4:
            level_guidance = "Nivel 1-4: Inventario mundano, pociones curativas básicas, quizás un objeto mágico común (de sabor)."
        elif level <= 10:
            level_guidance = "Nivel 5-10: Armas +1, pociones variadas, objetos Poco Comunes (Uncommon)."
        elif level <= 16:
            level_guidance = "Nivel 11-16: Armas +2, armaduras mágicas, objetos Raros (Rare)."
        else:
            level_guidance = "Nivel 17-20: Objetos Muy Raros o Legendarios, precios exorbitantes."

        system = """
        You are an expert D&D 5e (2024) merchant. Generate a detailed and BALANCED shop.
        Always respond with this exact JSON (English snake_case) English keys and Spanish values:
        {
            "name": "Creative Shop Name",
            "type": "Shop Type",
            "location": "City or place",
            "description": "Visual and olfactory description of the shop.",
            "shopkeeper_name": "Shopkeeper Name",
            "shopkeeper_race": "Race",
            "shopkeeper_personality": "Personality or physical trait.",
            "inventory": [
                {"name": "Item Name", "price": "X gp", "stock": 1, "detail": "Brief detail (e.g: +1, rusty)"}
            ],
            "special_feature": "Something unique (e.g: discount for bards, illegal back room)."
        }
        """

        prompt = f"""
        Generate a shop of type "{shop_type}" suitable for adventuring party at LEVEL {level}.
        {context_loc}

        INVENTORY GUIDELINES:
        {level_guidance}

        Generate 5 to 10 items appropriate for this power level and economy.
        
        CRITICAL: Use English keys (snake_case) English keys and Spanish values:
        "name", "type", "location", "description", "shopkeeper_name", "shopkeeper_race", 
        "shopkeeper_personality", "inventory" (array), "special_feature"
        Return ONLY valid JSON.
        """

        result = self._generate_content(system, prompt)
        print(f"[LOG] Shop generated by Gemini: {result}")  # DEBUG
        return result


shop_service = ShopService()