from app.services.gemini_service import BaseService


class SpellService(BaseService):
    def generate_spell(self, description, level=None):
        lvl_str = f"Level {level}" if level is not None else "of appropriate power"

        system_instruction = """
        You are an Archmage expert in creating new (Homebrew) spells for D&D 5e (2024).
        Your absolute priority is MATHEMATICAL BALANCE. Use the "Dungeon Master's Guide" for damage/effect per level.

        Generate ALWAYS a valid JSON with this structure (English snake_case) English keys and Spanish values:
        {
            "name": "Arcane Spell Name",
            "level": 3,
            "school": "Evocation",
            "casting_time": "1 action",
            "range": "60 feet (18 m)",
            "components": "V, S, M (material description)",
            "duration": "Instantaneous or Concentration, up to 1 minute",
            "description": "Complete spell text with D&D technical language. Use saving throws, damage rolls, conditions.",
            "upcast": "Text for upcast (empty if not applicable)"
        }
        """

        prompt = f"""
        Design a new spell of {lvl_str} based on this idea: "{description}".
        Make it creative but mechanically fair.
        
        CRITICAL: Use English keys (snake_case) English keys and Spanish values:
        "name", "level" (as number), "school", "casting_time", "range", "components", "duration", "description", "upcast"
        Do NOT include "classes" - that's managed in the database separately.
        Do NOT use Spanish keys like "nombre", "escuela", "mejora_nivel_superior".
        """

        result = self._generate_content(system_instruction, prompt)
        print(f"[LOG] Spell generated by Gemini: {result}")  # DEBUG
        return result


spell_service = SpellService()